KEY: "YOUR-KEY-HERE"

KICK_MESSAGE:
  - "&b&lNet&9&lShield &7&m-&f Blocked"
  - "&f"
  - "&cYour account is blocked from the &lNetShield&c network."
  - "&cIf you think this is an error. Contact us at Discord."
  - "&f"
  - "&9Discord &7» &fdiscord.gg/netshield"