KEY: "YOUR-KEY-HERE"

KICK_ON_CODES:
  - "BLOCKED"
  - "BOGON_IP"

MESSAGES:
  bogon_ip:
    - "&#fe5a61NetShield &7| &#ed3e6cDirecci贸n IP invalida"
    - "&f"
    - "&7Se ha detectado un inicio de sesi贸n desde una IP no valida."
    - "&7Si crees que es un error, crea un ticket en nuestro Discord."
    - "&f"
    - "&#7289da&odiscord.netshield.today"

  blocked:
    - "&#fe5a61NetShield &7| &#ed3e6cConexi贸n bloqueada"
    - "&f"
    - "&7Tu conexi贸n ha sido bloqueada por motivos de seguridad."
    - "&7Si crees que es un error, crea un ticket en nuestro Discord."
    - "&f"
    - "&#7289da&odiscord.netshield.today"

  default_kick:
    - "You are not allowed to connect."
    - "Please contact support for assistance."